source 'http://rubygems.org'

gem 'jekyll'
gem 'jekyll-paginate'
gem 'jekyll-gist'
gem 'kramdown'
gem 'rouge'
gem 'jekyll-youtube'
gem 'jekyll-vimeo'
gem 'jekyll-feed'
gem 'classifier-reborn'
gem 'rb-gsl'
